// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nekomeowww/insights-bot/ent/internal"
	"github.com/nekomeowww/insights-bot/ent/predicate"
	"github.com/nekomeowww/insights-bot/ent/telegramchat"
)

// TelegramChatQuery is the builder for querying TelegramChat entities.
type TelegramChatQuery struct {
	config
	ctx        *QueryContext
	order      []telegramchat.OrderOption
	inters     []Interceptor
	predicates []predicate.TelegramChat
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TelegramChatQuery builder.
func (tcq *TelegramChatQuery) Where(ps ...predicate.TelegramChat) *TelegramChatQuery {
	tcq.predicates = append(tcq.predicates, ps...)
	return tcq
}

// Limit the number of records to be returned by this query.
func (tcq *TelegramChatQuery) Limit(limit int) *TelegramChatQuery {
	tcq.ctx.Limit = &limit
	return tcq
}

// Offset to start from.
func (tcq *TelegramChatQuery) Offset(offset int) *TelegramChatQuery {
	tcq.ctx.Offset = &offset
	return tcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tcq *TelegramChatQuery) Unique(unique bool) *TelegramChatQuery {
	tcq.ctx.Unique = &unique
	return tcq
}

// Order specifies how the records should be ordered.
func (tcq *TelegramChatQuery) Order(o ...telegramchat.OrderOption) *TelegramChatQuery {
	tcq.order = append(tcq.order, o...)
	return tcq
}

// First returns the first TelegramChat entity from the query.
// Returns a *NotFoundError when no TelegramChat was found.
func (tcq *TelegramChatQuery) First(ctx context.Context) (*TelegramChat, error) {
	nodes, err := tcq.Limit(1).All(setContextOp(ctx, tcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{telegramchat.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tcq *TelegramChatQuery) FirstX(ctx context.Context) *TelegramChat {
	node, err := tcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TelegramChat ID from the query.
// Returns a *NotFoundError when no TelegramChat ID was found.
func (tcq *TelegramChatQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = tcq.Limit(1).IDs(setContextOp(ctx, tcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{telegramchat.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tcq *TelegramChatQuery) FirstIDX(ctx context.Context) int64 {
	id, err := tcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TelegramChat entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TelegramChat entity is found.
// Returns a *NotFoundError when no TelegramChat entities are found.
func (tcq *TelegramChatQuery) Only(ctx context.Context) (*TelegramChat, error) {
	nodes, err := tcq.Limit(2).All(setContextOp(ctx, tcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{telegramchat.Label}
	default:
		return nil, &NotSingularError{telegramchat.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tcq *TelegramChatQuery) OnlyX(ctx context.Context) *TelegramChat {
	node, err := tcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TelegramChat ID in the query.
// Returns a *NotSingularError when more than one TelegramChat ID is found.
// Returns a *NotFoundError when no entities are found.
func (tcq *TelegramChatQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = tcq.Limit(2).IDs(setContextOp(ctx, tcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{telegramchat.Label}
	default:
		err = &NotSingularError{telegramchat.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tcq *TelegramChatQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := tcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TelegramChats.
func (tcq *TelegramChatQuery) All(ctx context.Context) ([]*TelegramChat, error) {
	ctx = setContextOp(ctx, tcq.ctx, "All")
	if err := tcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TelegramChat, *TelegramChatQuery]()
	return withInterceptors[[]*TelegramChat](ctx, tcq, qr, tcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tcq *TelegramChatQuery) AllX(ctx context.Context) []*TelegramChat {
	nodes, err := tcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TelegramChat IDs.
func (tcq *TelegramChatQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if tcq.ctx.Unique == nil && tcq.path != nil {
		tcq.Unique(true)
	}
	ctx = setContextOp(ctx, tcq.ctx, "IDs")
	if err = tcq.Select(telegramchat.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tcq *TelegramChatQuery) IDsX(ctx context.Context) []int64 {
	ids, err := tcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tcq *TelegramChatQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tcq.ctx, "Count")
	if err := tcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tcq, querierCount[*TelegramChatQuery](), tcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tcq *TelegramChatQuery) CountX(ctx context.Context) int {
	count, err := tcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tcq *TelegramChatQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tcq.ctx, "Exist")
	switch _, err := tcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tcq *TelegramChatQuery) ExistX(ctx context.Context) bool {
	exist, err := tcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TelegramChatQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tcq *TelegramChatQuery) Clone() *TelegramChatQuery {
	if tcq == nil {
		return nil
	}
	return &TelegramChatQuery{
		config:     tcq.config,
		ctx:        tcq.ctx.Clone(),
		order:      append([]telegramchat.OrderOption{}, tcq.order...),
		inters:     append([]Interceptor{}, tcq.inters...),
		predicates: append([]predicate.TelegramChat{}, tcq.predicates...),
		// clone intermediate query.
		sql:  tcq.sql.Clone(),
		path: tcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TelegramChat.Query().
//		GroupBy(telegramchat.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tcq *TelegramChatQuery) GroupBy(field string, fields ...string) *TelegramChatGroupBy {
	tcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TelegramChatGroupBy{build: tcq}
	grbuild.flds = &tcq.ctx.Fields
	grbuild.label = telegramchat.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//	}
//
//	client.TelegramChat.Query().
//		Select(telegramchat.FieldType).
//		Scan(ctx, &v)
func (tcq *TelegramChatQuery) Select(fields ...string) *TelegramChatSelect {
	tcq.ctx.Fields = append(tcq.ctx.Fields, fields...)
	sbuild := &TelegramChatSelect{TelegramChatQuery: tcq}
	sbuild.label = telegramchat.Label
	sbuild.flds, sbuild.scan = &tcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TelegramChatSelect configured with the given aggregations.
func (tcq *TelegramChatQuery) Aggregate(fns ...AggregateFunc) *TelegramChatSelect {
	return tcq.Select().Aggregate(fns...)
}

func (tcq *TelegramChatQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tcq); err != nil {
				return err
			}
		}
	}
	for _, f := range tcq.ctx.Fields {
		if !telegramchat.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tcq.path != nil {
		prev, err := tcq.path(ctx)
		if err != nil {
			return err
		}
		tcq.sql = prev
	}
	return nil
}

func (tcq *TelegramChatQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TelegramChat, error) {
	var (
		nodes = []*TelegramChat{}
		_spec = tcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TelegramChat).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TelegramChat{config: tcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = tcq.schemaConfig.TelegramChat
	ctx = internal.NewSchemaConfigContext(ctx, tcq.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tcq *TelegramChatQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tcq.querySpec()
	_spec.Node.Schema = tcq.schemaConfig.TelegramChat
	ctx = internal.NewSchemaConfigContext(ctx, tcq.schemaConfig)
	_spec.Node.Columns = tcq.ctx.Fields
	if len(tcq.ctx.Fields) > 0 {
		_spec.Unique = tcq.ctx.Unique != nil && *tcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tcq.driver, _spec)
}

func (tcq *TelegramChatQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(telegramchat.Table, telegramchat.Columns, sqlgraph.NewFieldSpec(telegramchat.FieldID, field.TypeInt64))
	_spec.From = tcq.sql
	if unique := tcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tcq.path != nil {
		_spec.Unique = true
	}
	if fields := tcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, telegramchat.FieldID)
		for i := range fields {
			if fields[i] != telegramchat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tcq *TelegramChatQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tcq.driver.Dialect())
	t1 := builder.Table(telegramchat.Table)
	columns := tcq.ctx.Fields
	if len(columns) == 0 {
		columns = telegramchat.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tcq.sql != nil {
		selector = tcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tcq.ctx.Unique != nil && *tcq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(tcq.schemaConfig.TelegramChat)
	ctx = internal.NewSchemaConfigContext(ctx, tcq.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range tcq.predicates {
		p(selector)
	}
	for _, p := range tcq.order {
		p(selector)
	}
	if offset := tcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TelegramChatGroupBy is the group-by builder for TelegramChat entities.
type TelegramChatGroupBy struct {
	selector
	build *TelegramChatQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tcgb *TelegramChatGroupBy) Aggregate(fns ...AggregateFunc) *TelegramChatGroupBy {
	tcgb.fns = append(tcgb.fns, fns...)
	return tcgb
}

// Scan applies the selector query and scans the result into the given value.
func (tcgb *TelegramChatGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tcgb.build.ctx, "GroupBy")
	if err := tcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TelegramChatQuery, *TelegramChatGroupBy](ctx, tcgb.build, tcgb, tcgb.build.inters, v)
}

func (tcgb *TelegramChatGroupBy) sqlScan(ctx context.Context, root *TelegramChatQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tcgb.fns))
	for _, fn := range tcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tcgb.flds)+len(tcgb.fns))
		for _, f := range *tcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TelegramChatSelect is the builder for selecting fields of TelegramChat entities.
type TelegramChatSelect struct {
	*TelegramChatQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tcs *TelegramChatSelect) Aggregate(fns ...AggregateFunc) *TelegramChatSelect {
	tcs.fns = append(tcs.fns, fns...)
	return tcs
}

// Scan applies the selector query and scans the result into the given value.
func (tcs *TelegramChatSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tcs.ctx, "Select")
	if err := tcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TelegramChatQuery, *TelegramChatSelect](ctx, tcs.TelegramChatQuery, tcs, tcs.inters, v)
}

func (tcs *TelegramChatSelect) sqlScan(ctx context.Context, root *TelegramChatQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tcs.fns))
	for _, fn := range tcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
