// Code generated by ent, DO NOT EDIT.

package telegramchat

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the telegramchat type in the database.
	Label = "telegram_chat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldIsForum holds the string denoting the is_forum field in the database.
	FieldIsForum = "is_forum"
	// Table holds the table name of the telegramchat in the database.
	Table = "telegram_chats"
)

// Columns holds all SQL columns for telegramchat fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldTitle,
	FieldUsername,
	FieldIsForum,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsForum holds the default value on creation for the "is_forum" field.
	DefaultIsForum bool
)

// OrderOption defines the ordering options for the TelegramChat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByIsForum orders the results by the is_forum field.
func ByIsForum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsForum, opts...).ToFunc()
}
